"""Ver 1.0

Revision ID: 06bf2369f346
Revises: f108ec510e43
Create Date: 2022-11-23 14:59:31.183497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bf2369f346'
down_revision = 'f108ec510e43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
