"""Ver 2.0

Revision ID: 32f8248c3d33
Revises: 9d31083dea8d
Create Date: 2022-11-23 15:28:33.399396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f8248c3d33'
down_revision = '9d31083dea8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
