"""Ver 2.0

Revision ID: 9d31083dea8d
Revises: 06bf2369f346
Create Date: 2022-11-23 15:24:59.917613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d31083dea8d'
down_revision = '06bf2369f346'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
