"""Big int

Revision ID: c419a2806c5d
Revises: 32f8248c3d33
Create Date: 2022-11-23 15:33:23.383007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c419a2806c5d'
down_revision = '32f8248c3d33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
