"""Ver 1.0

Revision ID: f108ec510e43
Revises: 
Create Date: 2022-11-23 01:37:06.340503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f108ec510e43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('courses', 'is_active')
    op.add_column('discussions', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('discussions', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('discussions', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('discussions', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('discussions', 'title')
    op.add_column('tasks', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('tasks', 'title')
    op.alter_column('users', 'moodle_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('users', 'moodle_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('tasks', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'name')
    op.add_column('discussions', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('discussions', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('discussions', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('discussions', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('discussions', 'name')
    op.add_column('courses', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
