version: "3.9"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  bot:
    build: .
    restart: always
    environment:
      - TZ=Europe/Moscow
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.4'
    depends_on:
      - db
