version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file:
      - .env
    volumes:
      - .:/var/lib/postgresql/data
    networks:
      - db
    ports:
      - "5432:5432"

  bot:
    build: .
    restart: always
    environment:
      - TZ=Europe/Moscow
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.4'
    networks:
      - db
    depends_on:
      - db

networks:
  db:
    driver: bridge